# Generated by Django 3.0.3 on 2020-02-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PertanyaanModel',
            fields=[
                ('id_pertanyaan', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pertanyaan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PilihanModel',
            fields=[
                ('id_pilihan', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pilihan', models.CharField(max_length=255)),
                ('vote', models.IntegerField(default=0)),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihan', to='vote.PertanyaanModel')),
            ],
        ),
    ]
